env:
  node: true
  es6: true
  mocha: true
extends: airbnb-base
parser: typescript-eslint-parser
parserOptions:
  sourceType: module
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
        - .d.ts
rules:
  import/no-extraneous-dependencies:
    - off
  no-unused-vars:
    - off
  no-undef:
    - off
